# Generated by Django 3.2 on 2021-09-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choresUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choresuser',
            name='profile_picture',
            field=models.ImageField(default='./default_profile_picture.png', upload_to='profile_pictures'),
        ),
    ]
