# Generated by Django 3.2 on 2021-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choresUser', '0002_choresuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choresuser',
            name='profile_picture',
            field=models.ImageField(default='choresUser/default_profile_picture.png', upload_to='profile_pictures'),
        ),
    ]
